[options]
; Database settings
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo_patco

; Server settings
xmlrpc_port = 8069
logfile = False
log_level = info

; Addons path
addons_path = addons,extra-addons,extra-addons/OCA/web,extra-addons/OCA/account-payment,extra-addons/OCA/maintenance,extra-addons/OCA/project,extra-addons/OCA/reporting-engine,extra-addons/OCA/server-env,extra-addons/OCA/hr,extra-addons/OCA/field-service,extra-addons/OCA/partner-contact,extra-addons/OCA/helpdesk

; Development settings
dev_mode = reload,qweb,werkzeug,xml
without_demo = False