[options]
; Configuración de desarrollo local para PACIFIC ALLIANCE TRADING COMPANY SAC

; Configuración de base de datos
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo-patco

; Configuración de servidor
xmlrpc_port = 8069
log_level = info

; Configuración de addons
addons_path = c:\Trabajo\odoo-patco\odoo\addons,c:\Trabajo\odoo-patco\extra-addons,c:\Trabajo\odoo-patco\extra-addons\OCA\web,c:\Trabajo\odoo-patco\extra-addons\OCA\account-payment,c:\Trabajo\odoo-patco\extra-addons\OCA\maintenance,c:\Trabajo\odoo-patco\extra-addons\OCA\project,c:\Trabajo\odoo-patco\extra-addons\OCA\reporting-engine,c:\Trabajo\odoo-patco\extra-addons\OCA\server-env,c:\Trabajo\odoo-patco\extra-addons\OCA\hr,c:\Trabajo\odoo-patco\extra-addons\OCA\field-service,c:\Trabajo\odoo-patco\extra-addons\OCA\partner-contact,c:\Trabajo\odoo-patco\extra-addons\OCA\helpdesk

; Configuración de seguridad
admin_passwd = admin

; Configuración de límites
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200

; Configuración de desarrollo
dev_mode = reload,qweb,werkzeug,xml
without_demo = False