[options]
; Configuración básica de Odoo para PACIFIC ALLIANCE TRADING COMPANY SAC

; Configuración de base de datos
db_host = db
db_port = 5432
db_user = odoo
db_password = P4tc0_2
db_name = odoo_patco

; Configuración de servidor
xmlrpc_port = 8069
; logfile = /var/log/odoo/odoo.log
log_level = info

; Configuración de addons
addons_path = /opt/odoo/addons,/mnt/extra-addons,/mnt/extra-addons/OCA/web,/mnt/extra-addons/OCA/account-payment,/mnt/extra-addons/OCA/maintenance,/mnt/extra-addons/OCA/project,/mnt/extra-addons/OCA/reporting-engine,/mnt/extra-addons/OCA/server-env,/mnt/extra-addons/OCA/hr,/mnt/extra-addons/OCA/field-service,/mnt/extra-addons/OCA/partner-contact,/mnt/extra-addons/OCA/helpdesk,/mnt/extra-addons/OCA/agreement,/mnt/extra-addons/OCA/fieldservice_skill

; Configuración de seguridad
admin_passwd = P4tc0_2

; Configuración de workers (para producción)
; workers = 4
; max_cron_threads = 2

; Configuración de límites
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200

; Configuración de proxy (si se usa)
; proxy_mode = True

; Configuración de desarrollo
; dev_mode = reload,qweb,werkzeug,xml

; --- Configuración de Inicialización ---
; --- without_demo = all